apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-route
  namespace: banking-app
  labels:
    app: api-service
spec:
  path: /api
  to:
    kind: Service
    name: api-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
