apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
  namespace: banking-app
  labels:
    app: frontend-service
spec:
  path: /
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
