apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: banking-app
  labels:
    app: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
        version: v1
        mesh-scope: critical
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker-service
          image: bankingappdev.azurecr.io/worker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 4000
          envFrom:
            - configMapRef:
                name: banking-app-config
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
