apiVersion: v1
data:
  AZURE_OPENAI_DEPLOYMENT: eW91ci1kZXBsb3ltZW50
  AZURE_OPENAI_ENDPOINT: eW91ci1lbmRwb2ludA==
  AZURE_OPENAI_KEY: eW91ci1rZXk=
kind: Secret
metadata:
  creationTimestamp: "2026-05-01T00:44:27Z"
  name: azure-openai-secret
  namespace: banking-app
  resourceVersion: "395150"
  uid: 05f41cf0-59ee-4b55-a03c-041bd8076214
type: Opaque
