trigger:
- main

variables:
  imageTag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Docker@2
  displayName: Build and Push banking-api
  inputs:
    command: buildAndPush
    repository: banking-api
    dockerfile: banking-api/Dockerfile
    containerRegistry: ACR-Service-Connection
    tags: |
      $(imageTag)
      latest