apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 5
        Log_Level info

    [INPUT]
        Name dummy
        Tag banking.test
        Dummy {"message":"Fluent Bit to Splunk test","service":"fluent-bit"}

    [OUTPUT]
        Name splunk
        Match *
        Host si-i-04008f45cec3298fd.prd-p-d0lkp.splunkcloud.com
        Port 8088
        TLS On
        Splunk_Token ${SPLUNK_HEC_TOKEN}
        Splunk_Send_Raw Off
