apiVersion: v1
data:
  DB_HOST: YmFua2luZy1hcHAtZGV2LXBnLTMxMDY1LnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_NAME: YmFua2luZw==
  DB_PASSWORD: QmFua2luZ3BFRllPUm1BOE81SHY0bk1GYU9ja3NQNiEx
  DB_PORT: NTQzMg==
  DB_USER: YmFua2luZ2FkbWlu
kind: Secret
metadata:
  creationTimestamp: "2026-05-01T00:40:31Z"
  labels:
    secrets-store.csi.k8s.io/managed: "true"
  name: postgres-secret-kv
  namespace: banking-app
  ownerReferences:
  - apiVersion: apps/v1
    kind: ReplicaSet
    name: api-service-76b446fbdf
    uid: 21a33da2-29fd-4cb3-8eb6-7822447048ec
  - apiVersion: apps/v1
    kind: ReplicaSet
    name: api-service-9886688c5
    uid: fa0cb21b-c089-4aa9-b7a3-18b176ee1345
  - apiVersion: apps/v1
    kind: ReplicaSet
    name: api-service-694f44d7c5
    uid: 332395e7-1d73-4824-a35c-4fb93036e9b5
  - apiVersion: apps/v1
    kind: ReplicaSet
    name: api-service-7c986cb8bc
    uid: 8c6df153-c4f9-44ce-a55e-f658301d9b16
  resourceVersion: "2087946"
  uid: 8d43d00a-9198-4993-b3a5-f974afa78097
type: Opaque
