apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-kv-secrets
  namespace: banking-app
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true" # Set to true if using managed identity for authentication
    userAssignedIdentityID: "15e5f581-ae8e-4905-917f-b46add268bed" # AKS Key Vault CSI identity client ID
    usePodIdentity: "false"
    keyvaultName: "banking-dev-kv-31065"
    tenantId: "385a89b9-c0e9-4284-804e-55f12c0b6424"
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
  secretObjects:
    - secretName: postgres-secret-kv
      type: Opaque
      data:
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-PORT
          key: DB_PORT
        - objectName: DB-USER
          key: DB_USER
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: DB-NAME
          key: DB_NAME
