apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: worker-service
  namespaceSelector:
    matchNames:
      - banking-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
