apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
spec:
  selector:
    matchLabels:
      app: worker-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s