apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-app-config
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  KAFKA_BROKER: {{ .Values.global.kafkaBroker | quote }}
  DB_SSL: {{ .Values.config.dbSsl | quote }}
  DD_ENV: {{ .Values.config.ddEnv | quote }}
  DD_VERSION: {{ .Values.config.ddVersion | quote }}
