{{- if .Values.apiService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.apiService.name }}
spec:
  type: {{ .Values.apiService.service.type }}
  selector:
    app: {{ .Values.apiService.name }}
  ports:
    - name: http
      port: {{ .Values.apiService.service.port }}
      targetPort: http
{{- end }}
{{- if and .Values.workerService.enabled .Values.workerService.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workerService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.workerService.name }}
spec:
  type: {{ .Values.workerService.service.type }}
  selector:
    app: {{ .Values.workerService.name }}
  ports:
    - name: metrics
      port: {{ .Values.workerService.service.port }}
      targetPort: metrics
{{- end }}
{{- if .Values.aiAnalyzerService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aiAnalyzerService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.aiAnalyzerService.name }}
spec:
  type: {{ .Values.aiAnalyzerService.service.type }}
  selector:
    app: {{ .Values.aiAnalyzerService.name }}
  ports:
    - name: http
      port: {{ .Values.aiAnalyzerService.service.port }}
      targetPort: http
{{- end }}
{{- if .Values.fraudService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fraudService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.fraudService.name }}
spec:
  type: {{ .Values.fraudService.service.type }}
  selector:
    app: {{ .Values.fraudService.name }}
  ports:
    - name: http
      port: {{ .Values.fraudService.service.port }}
      targetPort: http
{{- end }}
{{- if .Values.dashboardService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dashboardService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.dashboardService.name }}
spec:
  type: {{ .Values.dashboardService.service.type }}
  selector:
    app: {{ .Values.dashboardService.name }}
  ports:
    - name: http
      port: {{ .Values.dashboardService.service.port }}
      targetPort: http
{{- end }}
{{- if .Values.frontendService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    app: {{ .Values.frontendService.name }}
spec:
  type: {{ .Values.frontendService.service.type }}
  selector:
    app: {{ .Values.frontendService.name }}
  ports:
    - name: http
      port: {{ .Values.frontendService.service.port }}
      targetPort: http
{{- end }}
