apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
data:
  NODE_ENV: development
  PORT: "3000"
  KAFKA_BROKER: kafka:9092
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: bankingdb
  POSTGRES_DB: bankingdb
  PGDATA: /var/lib/postgresql/data/pgdata