namespaceOverride: banking-prod

config:
  ddEnv: prod

apiService:
  replicaCount: 2
  image:
    tag: v5
  hpa:
    minReplicas: 2
    maxReplicas: 5

workerService:
  replicaCount: 2
  image:
    tag: v4

frontendService:
  replicaCount: 2

dashboardService:
  replicaCount: 2

ingress:
  host: ""
