from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "Banking-Microservices-AKS-Project.pptx"

SLIDE_W = 13_333_500
SLIDE_H = 7_500_000


slides = [
    {
        "title": "Banking Microservices on AKS",
        "subtitle": "Terraform, GitHub Actions, AKS, PostgreSQL, Kafka, Key Vault, Helm, Prometheus",
        "bullets": [
            "Cloud-native banking transaction workflow deployed to Azure Kubernetes Service.",
            "Infrastructure is managed with Terraform and remote state in Azure Storage.",
            "Application delivery uses GitHub Actions, ACR, and Helm.",
        ],
    },
    {
        "title": "Project Goals",
        "bullets": [
            "Deploy a production-style microservices stack to AKS.",
            "Use Terraform for repeatable Azure infrastructure.",
            "Use GitHub OIDC instead of long-lived Azure client secrets.",
            "Store database credentials in Azure Key Vault and sync them to Kubernetes.",
            "Add observability hooks with Prometheus metrics and alerting manifests.",
        ],
    },
    {
        "title": "Application Components",
        "bullets": [
            "api-service: Express API for creating, processing, and listing banking transactions.",
            "worker-service: consumes Kafka transaction messages and calls the API process endpoint.",
            "ai-analyzer-service: receives Alertmanager webhooks and sends incident context to Azure OpenAI.",
            "PostgreSQL Flexible Server: persistent store for banking transactions.",
            "Strimzi Kafka: internal event bus for transaction processing.",
        ],
    },
    {
        "title": "High-Level Architecture",
        "bullets": [
            "Client or ingress calls api-service on port 3000.",
            "api-service writes PENDING transaction rows to PostgreSQL.",
            "api-service publishes transaction messages to Kafka topic transactions.",
            "worker-service consumes Kafka messages and marks transactions PROCESSED through the API.",
            "Prometheus scrapes /metrics and Alertmanager can notify ai-analyzer-service.",
        ],
    },
    {
        "title": "Azure Infrastructure",
        "bullets": [
            "Resource group: rg-banking-app-dev.",
            "AKS cluster: banking-app-dev-aks in Canada Central.",
            "ACR: bankingappdev.azurecr.io for service images.",
            "Key Vault: banking-dev-kv-31065 for application secrets.",
            "PostgreSQL: banking-app-dev-pg-31065.postgres.database.azure.com.",
            "Terraform state: Azure Storage account bankingtfstate31065, container tfstate.",
        ],
    },
    {
        "title": "Terraform Layout",
        "bullets": [
            "terraform/main.tf creates Azure resource group, ACR import, AKS, PostgreSQL, Key Vault, role assignments, and GitHub OIDC identity.",
            "terraform/backend.tf configures the azurerm remote state backend.",
            "terraform/outputs.tf prints AKS, ACR, Key Vault, tenant, subscription, and GitHub client ID outputs.",
            "terraform/02-cluster-addons is intended for cluster add-ons such as controllers and platform services.",
        ],
    },
    {
        "title": "GitHub Actions Flow",
        "bullets": [
            "Terraform workflow runs fmt, init, validate, and plan on infrastructure changes.",
            "Manual workflow_dispatch with apply=true applies Terraform from main.",
            "Build and Deploy to AKS workflow builds Docker images and pushes to ACR.",
            "Helm deploys api-service, worker-service, and ai-analyzer-service to the banking-app namespace.",
            "GitHub OIDC authenticates to Azure without storing an Azure client secret.",
        ],
    },
    {
        "title": "Kubernetes Deployment",
        "bullets": [
            "Helm chart path: helm/banking-app.",
            "Namespace: banking-app.",
            "api-service uses postgres-secret-kv generated by Secrets Store CSI Driver.",
            "worker-service uses internal API URL http://api-service:3000 and Kafka bootstrap service.",
            "Kafka bootstrap endpoint: my-cluster-kafka-bootstrap.kafka.svc:9092.",
        ],
    },
    {
        "title": "Secrets and Identity",
        "bullets": [
            "postgres-spc.yaml defines SecretProviderClass postgres-kv-secrets.",
            "AKS Key Vault CSI identity client ID is used as userAssignedIdentityID.",
            "Key Vault secrets DB-HOST, DB-PORT, DB-USER, DB-PASSWORD, DB-NAME sync into Kubernetes secret postgres-secret-kv.",
            "GitHub Actions secrets include AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID, and POSTGRES_ADMIN_PASSWORD.",
        ],
    },
    {
        "title": "Kafka and Strimzi",
        "bullets": [
            "The installed Strimzi CRDs serve kafka.strimzi.io/v1.",
            "Kafka cluster now uses KafkaNodePool plus Kafka custom resources.",
            "single-node KafkaNodePool has one pod with broker and controller roles.",
            "transactions-topic.yaml creates KafkaTopic transactions with one partition and one replica.",
        ],
    },
    {
        "title": "Observability",
        "bullets": [
            "api-service exposes /metrics with HTTP request, latency, transaction, and error metrics.",
            "worker-service exposes /metrics on port 4000 with Kafka processing counters.",
            "worker-service-monitor.yaml defines a ServiceMonitor for Prometheus Operator.",
            "worker-kafka-alerts.yaml defines an alert for Kafka worker processing errors.",
            "ai-analyzer-service can receive Alertmanager webhooks and summarize incidents.",
        ],
    },
    {
        "title": "Issues Found: Infrastructure",
        "bullets": [
            "Microsoft.Storage and other Azure resource providers were not registered; provider registration was required.",
            "Terraform backend initially failed with blob RBAC propagation delay; access key was used for first backend initialization.",
            "Existing rg-banking-app-dev resource group had to be imported into Terraform state.",
            "Existing ACR bankingappdev had to be imported and app image references updated.",
            "Globally unique Key Vault name banking-app-dev-kv was unavailable, so banking-dev-kv-31065 was used.",
        ],
    },
    {
        "title": "Issues Found: AKS and PostgreSQL",
        "bullets": [
            "Standard_B2s was not allowed in eastus for this subscription.",
            "PostgreSQL Flexible Server was restricted in eastus for this subscription.",
            "Canada Central had only 2 vCPU quota available, so AKS was reduced to one Standard_D2s_v3 node.",
            "A failed PostgreSQL name attempt caused a name/location conflict, so server name became banking-app-dev-pg-31065.",
            "Final Terraform drift check was cleaned by codifying AKS OIDC issuer and node pool upgrade defaults.",
        ],
    },
    {
        "title": "Issues Found: Kubernetes",
        "bullets": [
            "api-service was stuck ContainerCreating because SecretProviderClass postgres-kv-secrets was missing.",
            "Fix: kubectl apply -f postgres-spc.yaml, then restart api-service.",
            "ai-analyzer-service CreateContainerConfigError commonly means azure-openai-secret is missing.",
            "Fix: create azure-openai-secret with endpoint, key, and deployment values, then restart ai-analyzer-service.",
            "Old pods may remain from previous Helm revisions until rollout completes or old ReplicaSets are scaled down.",
        ],
    },
    {
        "title": "Issues Found: Kafka",
        "bullets": [
            "kubectl apply failed: no matches for kind Kafka in kafka.strimzi.io/v1beta2.",
            "Root cause: installed Strimzi CRDs only served v1.",
            "After changing to v1, strict schema rejected old zookeeper, replicas, and storage fields.",
            "Fix: convert Kafka manifest to Strimzi v1 with KafkaNodePool and KRaft-style single-node broker/controller.",
            "transactions KafkaTopic was also updated from v1beta2 to v1.",
        ],
    },
    {
        "title": "Troubleshooting Commands",
        "bullets": [
            "kubectl describe pod -n banking-app <pod> to inspect scheduling, image, secret, and volume events.",
            "kubectl get secretproviderclass -n banking-app to verify CSI secret provider resources.",
            "kubectl get secret postgres-secret-kv -n banking-app to confirm synced DB secret.",
            "kubectl get kafka,kafkanodepool,kafkatopic -n kafka to check Strimzi resources.",
            "terraform -chdir=terraform plan to detect infrastructure drift.",
        ],
    },
    {
        "title": "Recovery Playbook",
        "bullets": [
            "Missing postgres-secret-kv: apply postgres-spc.yaml and restart api-service.",
            "Kafka CRD version mismatch: check kubectl get crd kafkas.kafka.strimzi.io -o jsonpath='{.spec.versions[*].name}'.",
            "Kafka not ready: inspect kubectl describe kafka -n kafka my-cluster and operator logs.",
            "Image pull failure: verify ACR name, image tag, and AcrPull assignment for AKS kubelet identity.",
            "GitHub Terraform failure: verify repo variables, secrets, and Storage Blob Data Contributor on remote state account.",
        ],
    },
    {
        "title": "Demo Script",
        "bullets": [
            "Show Terraform outputs and no-change plan.",
            "Show AKS node readiness with kubectl get nodes.",
            "Show Kafka readiness and transactions topic readiness.",
            "Show banking-app pods and services.",
            "Create a transaction through api-service, then confirm worker-service processes it.",
            "Show Prometheus metrics endpoint for api-service and worker-service.",
        ],
    },
    {
        "title": "Current Status",
        "bullets": [
            "Terraform infrastructure applied successfully with no drift.",
            "AKS node verified Ready.",
            "PostgreSQL Flexible Server verified Ready.",
            "Kafka and transactions topic verified Ready after Strimzi v1 conversion.",
            "Remaining app readiness depends on applying postgres-spc.yaml and creating azure-openai-secret when needed.",
        ],
    },
]


def text_box_xml(shape_id, x, y, cx, cy, text, font_size=2800, bold=False, color="1F2937"):
    safe = escape(text)
    b = '<a:b/>' if bold else ''
    return f"""
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="{shape_id}" name="TextBox {shape_id}"/>
          <p:cNvSpPr txBox="1"/>
          <p:nvPr/>
        </p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
          <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
          <a:noFill/><a:ln><a:noFill/></a:ln>
        </p:spPr>
        <p:txBody>
          <a:bodyPr wrap="square" anchor="t"/>
          <a:lstStyle/>
          <a:p>
            <a:r>
              <a:rPr lang="en-US" sz="{font_size}">{b}<a:solidFill><a:srgbClr val="{color}"/></a:solidFill></a:rPr>
              <a:t>{safe}</a:t>
            </a:r>
            <a:endParaRPr lang="en-US" sz="{font_size}"/>
          </a:p>
        </p:txBody>
      </p:sp>
"""


def bullets_xml(shape_id, bullets, x=800_000, y=1_650_000, cx=11_800_000, cy=5_300_000):
    paragraphs = []
    for item in bullets:
        safe = escape(item)
        paragraphs.append(f"""
          <a:p>
            <a:pPr marL="330200" indent="-228600">
              <a:buFont typeface="Arial"/>
              <a:buChar char="•"/>
            </a:pPr>
            <a:r>
              <a:rPr lang="en-US" sz="2400"><a:solidFill><a:srgbClr val="111827"/></a:solidFill></a:rPr>
              <a:t>{safe}</a:t>
            </a:r>
            <a:endParaRPr lang="en-US" sz="2400"/>
          </a:p>
""")
    return f"""
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="{shape_id}" name="Bullets {shape_id}"/>
          <p:cNvSpPr txBox="1"/>
          <p:nvPr/>
        </p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
          <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
          <a:noFill/><a:ln><a:noFill/></a:ln>
        </p:spPr>
        <p:txBody>
          <a:bodyPr wrap="square" anchor="t"/>
          <a:lstStyle/>
          {''.join(paragraphs)}
        </p:txBody>
      </p:sp>
"""


def rect_xml(shape_id, x, y, cx, cy, fill, line=None):
    line_xml = f'<a:ln><a:solidFill><a:srgbClr val="{line}"/></a:solidFill></a:ln>' if line else '<a:ln><a:noFill/></a:ln>'
    return f"""
      <p:sp>
        <p:nvSpPr><p:cNvPr id="{shape_id}" name="Rect {shape_id}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
          <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
          <a:solidFill><a:srgbClr val="{fill}"/></a:solidFill>
          {line_xml}
        </p:spPr>
      </p:sp>
"""


def slide_xml(slide, index):
    title = slide["title"]
    subtitle = slide.get("subtitle")
    title_size = 4200 if index == 1 else 3400
    body_y = 2_150_000 if subtitle else 1_550_000
    parts = [
        rect_xml(2, 0, 0, SLIDE_W, 250_000, "2563EB"),
        rect_xml(3, 0, 7_250_000, SLIDE_W, 250_000, "10B981"),
        text_box_xml(4, 700_000, 520_000, 12_000_000, 650_000, title, title_size, True, "0F172A"),
    ]
    next_id = 5
    if subtitle:
        parts.append(text_box_xml(next_id, 720_000, 1_180_000, 11_900_000, 500_000, subtitle, 2200, False, "475569"))
        next_id += 1
    parts.append(bullets_xml(next_id, slide["bullets"], y=body_y, cy=6_900_000 - body_y))
    parts.append(text_box_xml(next_id + 1, 11_900_000, 7_000_000, 800_000, 250_000, str(index), 1400, False, "64748B"))
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
       xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="{SLIDE_W}" cy="{SLIDE_H}"/><a:chOff x="0" y="0"/><a:chExt cx="{SLIDE_W}" cy="{SLIDE_H}"/></a:xfrm></p:grpSpPr>
      {''.join(parts)}
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>
"""


def write_pptx():
    OUT.parent.mkdir(exist_ok=True)
    slide_count = len(slides)

    content_types = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">',
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>',
        '<Default Extension="xml" ContentType="application/xml"/>',
        '<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>',
        '<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>',
        '<Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>',
        '<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>',
        '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>',
        '<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>',
    ]
    for i in range(1, slide_count + 1):
        content_types.append(f'<Override PartName="/ppt/slides/slide{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>')
    content_types.append("</Types>")

    presentation_rels = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
                         '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">']
    slide_ids = []
    for i in range(1, slide_count + 1):
        rid = f"rId{i}"
        slide_ids.append(f'<p:sldId id="{255+i}" r:id="{rid}"/>')
        presentation_rels.append(f'<Relationship Id="{rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{i}.xml"/>')
    presentation_rels.append(f'<Relationship Id="rId{slide_count+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>')
    presentation_rels.append("</Relationships>")

    presentation = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
                xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
                xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId{slide_count+1}"/></p:sldMasterIdLst>
  <p:sldIdLst>{''.join(slide_ids)}</p:sldIdLst>
  <p:sldSz cx="{SLIDE_W}" cy="{SLIDE_H}" type="wide"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>
"""

    root_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>
"""

    core = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
                   xmlns:dc="http://purl.org/dc/elements/1.1/"
                   xmlns:dcterms="http://purl.org/dc/terms/"
                   xmlns:dcmitype="http://purl.org/dc/dcmitype/"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>Banking Microservices on AKS</dc:title>
  <dc:subject>Project presentation and troubleshooting guide</dc:subject>
  <dc:creator>Codex</dc:creator>
</cp:coreProperties>
"""

    app = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
            xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Codex</Application>
  <PresentationFormat>Widescreen</PresentationFormat>
  <Slides>{slide_count}</Slides>
</Properties>
"""

    slide_layout = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
             xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
             xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank">
  <p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sldLayout>
"""

    slide_master = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
             xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
             xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="2563EB" accent2="10B981" accent3="F59E0B" accent4="EF4444" accent5="64748B" accent6="0F172A" hlink="2563EB" folHlink="7C3AED"/>
  <p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>
  <p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles>
</p:sldMaster>
"""

    master_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>
</Relationships>
"""

    empty_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>
"""

    theme = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Banking Theme">
  <a:themeElements>
    <a:clrScheme name="Banking">
      <a:dk1><a:srgbClr val="0F172A"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1>
      <a:dk2><a:srgbClr val="1E293B"/></a:dk2><a:lt2><a:srgbClr val="F8FAFC"/></a:lt2>
      <a:accent1><a:srgbClr val="2563EB"/></a:accent1><a:accent2><a:srgbClr val="10B981"/></a:accent2>
      <a:accent3><a:srgbClr val="F59E0B"/></a:accent3><a:accent4><a:srgbClr val="EF4444"/></a:accent4>
      <a:accent5><a:srgbClr val="64748B"/></a:accent5><a:accent6><a:srgbClr val="0F172A"/></a:accent6>
      <a:hlink><a:srgbClr val="2563EB"/></a:hlink><a:folHlink><a:srgbClr val="7C3AED"/></a:folHlink>
    </a:clrScheme>
    <a:fontScheme name="Arial"><a:majorFont><a:latin typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Arial"/></a:minorFont></a:fontScheme>
    <a:fmtScheme name="Default"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme>
  </a:themeElements>
</a:theme>
"""

    with ZipFile(OUT, "w", ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", "\n".join(content_types))
        z.writestr("_rels/.rels", root_rels)
        z.writestr("docProps/core.xml", core)
        z.writestr("docProps/app.xml", app)
        z.writestr("ppt/presentation.xml", presentation)
        z.writestr("ppt/_rels/presentation.xml.rels", "\n".join(presentation_rels))
        z.writestr("ppt/slideMasters/slideMaster1.xml", slide_master)
        z.writestr("ppt/slideMasters/_rels/slideMaster1.xml.rels", master_rels)
        z.writestr("ppt/slideLayouts/slideLayout1.xml", slide_layout)
        z.writestr("ppt/slideLayouts/_rels/slideLayout1.xml.rels", empty_rels)
        z.writestr("ppt/theme/theme1.xml", theme)
        for i, slide in enumerate(slides, 1):
            z.writestr(f"ppt/slides/slide{i}.xml", slide_xml(slide, i))
            z.writestr(f"ppt/slides/_rels/slide{i}.xml.rels", empty_rels)


if __name__ == "__main__":
    write_pptx()
    print(OUT)
