apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  namespace: openshif-tbanking-ap-dev
spec:
  serviceAccountName: banking-api-sa
  containers:
    - name: test
      image: registry.access.redhat.com/ubi9/ubi
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL