apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiService.name }}
  labels:
    app: {{ .Values.apiService.name }}
spec:
  type: {{ .Values.apiService.service.type }}
  selector:
    app: {{ .Values.apiService.name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.apiService.service.port }}
      targetPort: {{ .Values.apiService.containerPort }}
