name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to apply"
        required: true
        default: "dev"
        type: choice
        options:
          - dev

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: openshift-azure-terraform/infra/live/${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        #code checkout

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.82.3
          wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Terragrunt Plan All
        run: terragrunt run-all plan --non-interactive

      - name: Terragrunt Apply All
        run: terragrunt run-all apply --non-interactive -auto-approve